// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import DayjsController from "./dayjs_controller"
application.register("dayjs", DayjsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocalTimeController from "./local_time_controller"
application.register("local-time", LocalTimeController)

import TempusDominusController from "./tempus_dominus_controller"
application.register("tempus-dominus", TempusDominusController)
