// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

import AutosubmitController from "controllers/autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import FlatpickrController from "controllers/flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import LocalTimeController from "controllers/local_time_controller"
application.register("local-time", LocalTimeController)
